[package]
name = "rust-clean-build"
version = "0.1.0"
description = "A Rust Console App"
authors = ["Hussein Dossoki"]
license = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "*"
futures = "0.3"
